### ISSUE TITLE
Availability via Bower

### ISSUE THREAD

**Issue by CupOfTea696** [mousetrap-js/mousetrap#4]
> Issue migrated from ccampbell/mousetrap#326

It would be great if it would be possible to install it via Bower.

**Comment by ghost** [comment]
So I presume this is not yet the case? Well I can validate that I guess:

![image](https://cloud.githubusercontent.com/assets/11848802/13221376/0a93964c-d973-11e5-9587-f25e83bdd692.png)

So no, doesn't seem like it. But what puzzles me is that, when looking at ccampbells repository, I'm missing the bower source files there which I thought would need to be present. How it ends up with bower is a mystery, to me...

`Packages are defined by a manifest file bower.json.`

Right, so that means it either used to have one and it got removed, or perhaps another branch while publishing back then. Anyway for your reference (the most relevant bits):
- The package name must adhere to the bower.json spec.
- There must be a valid bower.json in the project’s root directory.
- Your package should use semver Git tags. The v prefix is allowed.
- Your package must be publically available at a Git endpoint (e.g., GitHub). Remember to push your Git tags!

Furthermore there is the notion that: `Bower doesn’t support GitHub-style namespacing (org/repo), however you are encouraged to namespace related packages with -` Source: http://bower.io/docs/creating-packages/#register

Looking at the list I notice there are a few possible releases besides the stock mousetrap of which I'm not sure (but guessing) they won't be as up-to-date as this one might be. (check mousetrap-latest igorsantana: july 2015, check mousetrap-min tylerlong: april 2015).

So to summarize, good job for picking this up, a few questions and pointers:
- when can we get this done? should I do a pull request? I really want to have it deployed as soon as possible
- what shall we name it? I think **mousetrapjs** is a suitable name for our purpose.

To be fair, I like it probably the most since there is always the chance that the original project really died (ccampbell remains unresponsive to the pull requests and issues) so we might be stuck with the name we pick for the foreseeable future. Hence names like _mousetrap-temp_ , _mousetrap-fork_ or _mousetrap-cupoftea_ and ilk all seem like the lesser options while risking that it will stick, and the whole world will end up using it after all (and not just us early birds who may more easily switch back should the project come back to life after all, I know I wouldn't mind).

**Comment by ghost** [comment]
Oh... `mousetrap-js` is an option I guess... dunno. I seem to prefer uses of concatenated `js` over `.` or `-` but to be frank: Tomayto, Tomahto as far as I'm concerned. But if I'm going to do the bower.json + pull it seems there may need to be a little consensus first (or I do it, possibly wrong, then on merge author can change it whatever he pleases, not that a biggie)

Cheers

**Comment by robincafolla** [comment]
@robjens I went with mousetrap-js for the repo name, so maybe that's the best option in terms of the bower package?

I don't use bower, so if you could issue a pull request that would be brilliant.

If you can't, I'm happy to work my way through the bower docs to get support added, but my time is a little limited atm, and it might have to wait a bit (maybe as long as a week).

**Comment by ghost** [comment]
Ok working om it. I see you didn't happen to have had bumped the version yet, so I'll also leave that at `1.5.3`.

One of the requirements of bower is using semver so what's good is that it's already using that. Now I am not sure if you need to bump it, I guess not for bower but take note of the `gitHead` and old url in `package.json` and for anything that _does_ point to it.

So, let me do a little more research in prepping you with some info, since it might involve updates although I'm not sure, it might autodetect semver (git tags).

---

Before doing anything, there are two foundational things that I feel are key to understanding how to effectively distribute your package through Bower:
1. Bower is built on top of git. You can't distribute your package through Bower without it being hosted at some git endpoint, whether that is at GitHub, Bitbucket or some other git hosting provider (maybe you host your own). **Effectively, when you register a package with Bower, you're telling it where it can access the contents of your package when consumers request to install it**, and which contents of your repository you want distributed to package consumers. For the purposes of this article, I will be using GitHub as an endpoint for reference.
2. Package versions are just git tags. We'll discuss this in more detail shortly, but effectively you need to know that making a new "release" of your package available in Bower is as simple as tagging a changeset in your git

---

Right. So publish a new tag (snapshots) and it'll seem to pick up on the changes. This implies I could also register it, but since it will require a bump to push through the latest bug fixes and all, this means I'd still publish the old mousetrap `1.5.3` version. So please be so kind to give it a nudge I guess.

`bower register mousetrap-js https://github.com/mousetrap-js/mousetrap/` should be all needed for it, PR on the way.

**Comment by ghost** [comment]
Yeah... I should definitely leave the key in your hands as:

```
$ bower login
Authenticate with GitHub and store credentials. Required to unregister packages.
```

To be able and remove/unregister a bower package.

**Comment by robincafolla** [comment]
Closed by https://github.com/mousetrap-js/mousetrap/pull/7
